### ISSUE TITLE
Feature Request: Needed windows binary in releases.

### ISSUE THREAD

**Issue by tuxfight3r** [armory-io/arm#6]
As most of the corporate environment uses windows workstation it would be good to have a windows binary. we can download source and cross compile for windows but most of the corporate environments is behind proxy and its really hard to download all the dependency go packages.

**Comment by Jossuecito** [comment]
Hi @tuxfight3r!
I just made a release 0.0.2 with the binaries. I will try to make a new one with a couple of samples on the zip file so it can be easy to see it working.

**Comment by Jossuecito** [comment]
Hi @tuxfight3r !
Release 0.0.4 is out now, it contains windows binaries and examples.
